breakpoints
liftedinit/manifest-app pull request #11
Opened 2024-11-07 02:30 UTC by chalabi2

- **bank page breakpoints || wallet breakpoints**

This PR will focus on finalizing tablet & mobile breakpoints in the web app. 

**PAGES**
- BANK X
- GROUPS
- ADMIN
- FACTORY

**UI ELEMENTS** 
- WALLET X
- FORMS
- CONTACTS X
- ENDPOINTS X

2024-11-21 14:10 UTC, fmorency requested changes
Thanks!

Few comments
1) Tests are broken
2) Address CodeRabbit comments

We can discuss the rest during our meeting today.

2024-11-22 02:01 UTC, chalabi2 commented on components/groups/components/groupProposals.tsx
> +    const threshold = BigInt(policyThreshold);
this is irrelevant, the threshold will always be passed as a string due to the parent

2024-11-22 02:16 UTC, chalabi2 commented on components/groups/forms/proposals/SuccessForm.tsx
> +          className="w-[calc(50%-12px)]"
button renders fine on mobile

2024-11-22 02:22 UTC, chalabi2 commented on components/react/StepIndicator.tsx
> +}
theres still duplicates this is unecessary it already works

2024-11-22 02:24 UTC, chalabi2 commented on components/react/mobileNav.tsx
> +  };
we are using daisy ui

2024-11-22 02:24 UTC, chalabi2 commented on components/react/mobileNav.tsx
> +          >
a tags cannot have div children

2024-11-22 02:26 UTC, chalabi2 commented on hooks/useQueries.ts
> +    const finalUrl = `${baseUrl}?${query.replace(/\s+/g, '')}&order=data->txResponse->height.desc${paginationParams}`;
sql injection into a query........

2024-11-22 02:27 UTC, chalabi2 commented on pages/factory/index.tsx
> +        <meta property="og:image" content="https://" />
dont have these yet

2024-11-22 04:17 UTC, chalabi2 commented
> Thanks!
> 
> Few comments
> 
>     1. Tests are broken
> 
>     2. Address CodeRabbit comments
> 
> 
> We can discuss the rest during our meeting today.

Tests are fixed, coderabbit recommendations have been implemented, ready for massive merge.

2024-11-22 13:46 UTC, fmorency approved these changes

2024-11-22 13:47 UTC, merged