chalabi/mobile on desktop
liftedinit/manifest-app pull request #150
Opened 2024-12-10 02:15 UTC by chalabi2

fixes #132

clears wallet states better so no hangups when attempting mobile connections then closing the modal

2024-12-10 15:22 UTC, fmorency commented
Hey @chalabi2, how does one test this feature on Manifest?

2024-12-16 14:41 UTC, fmorency requested changes
Awesome!

@chalabi2 can you fix the conflicts, please?

2024-12-18 23:29 UTC, chalabi2 commented
@fmorency 

Couple things here

- Cosmostation does not have a qr code scanner in their wallet for wallet connections so i removed that. 
- I believe Leap mobile does not support "Suggest Chain" functionality so the chain needs to be added to the leap mobile wallet for QrCode and mobile wallet connections. This indicates its not an issue with the code but needs additional configuration on the mobile app. 

- isMobile determines if it is actually a mobile device or not, which allows different connection types depending on if we are on desktop or mobile, that means no qrCode on mobile but direct connection. 

- QrCode renders when the qrUri is available.  Allows to show loading qr code message. If a connection was already made (if youve already scanned the qr code) the connection will be re-established.

2024-12-19 13:58 UTC, fmorency approved these changes
I tested Keplr and it works, thank you!

This PR also contains the email/sms PR which is not working.

I thing the PRs should be merged in the following order

1. Fix the email/sms PR (SMS rendering is broken)
2. Merge the email/sms PR
3. Update this PR with the latest changes
4. Merge this PR

2024-12-19 19:35 UTC, chalabi2 commented
> I tested Keplr and it works, thank you!
> 
> This PR also contains the email/sms PR which is not working.
> 
> I thing the PRs should be merged in the following order
> 
>     1. Fix the email/sms PR (SMS rendering is broken)
> 
>     2. Merge the email/sms PR
> 
>     3. Update this PR with the latest changes
> 
>     4. Merge this PR

On it. I mistakenly left emoji's in the SMS input rendering lol.

2024-12-20 18:20 UTC, fmorency commented
@chalabi2 can you fix the conflicts? I'll merge after this is done.

2025-01-06 14:36 UTC, merged